- request_path: 'GET /users'
  contents:
    - '{ "name": "retu", "age" : "20" }'
    - '{ "name": "jane", "age" : "25" }'
- request_path: 'POST /user'
  status: 201
  contents:
    - '{ "name": "taro", "age" : 17 }'
